config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
    resources :messages
  end

  devise_for :users, controllers: {
      registrations: "users/registrations",
      omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index]
  resources :relationships, only: [:create, :destroy]

  root 'topics#index'
  resources :topics do
    resources :comments
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topic = Topic.new
    @topics = Topic.order("created_at DESC")
  end

  def new
  end

  def create
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id
      if @topic.save
        redirect_to action: :index
        NoticeMailer.sendmail_topic(@topic).deliver
      else
        redirect_to topics_path, notice: '文字を入力してください'
      end
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
  end

  def edit
    #code
  end

  def update
    if @topic.update(topics_params)
    redirect_to topics_path
    else
      render 'edit'
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path
  end

private
  def topics_params
    params.require(:topic).permit(:content)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<%= form_for @topic do |f| %>
  <%= f.text_field :content, placeholder: "今なにしてる？" %>
  <%= f.submit "編集する" %>
<% end %>

app/views/topics/index.html.erb
<p><%= flash[:notice] %></p>
<p><%= flash[:alert] %></p>



<%= form_for @topic do |f| %>
<% if @topic.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <h2><%= @topic.errors.count %>件のエラーがあります。</h2>

      <%= @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <%= f.text_field :content, placeholder: "今なにしてる？" %>
  <br>
  <%= f.submit "投稿"%>
<% end %>



<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <% @topics.each do |topic| %>
      <div class="row">
        <div style="background-color: white; width: 500px; height: 400px; margin: 0 auto; margin-top: 50px;">
          <div style="text-align: left; padding: 15px;">

          <%= profile_img(topic.user) %>

          <%= topic.user.name %>
        <%= link_to topic_path(topic) do %>
          </div>
          <div style="text-align: left; padding: 15px; width: 50%; border-top: 1px solid gray;">
            <%= topic.content %>
          </div>

            <%= link_to "詳細", topic_path(topic.id) %>
          <% if topic.user_id == current_user.id%>
            <%= link_to "編集", edit_topic_path(topic.id) %>
            <%= link_to "削除", topic_path(topic.id), method: :delete, data: {confirm: "削除しますか？"} %>
          <% end %>
        </div>
        <% end %>
        <% if topic.comments.exists? %>
          <p style="padding: 10px;">コメントを表示</p>
        <% end %>
            <% topic.comments.each do |comment| %>
              <div class="comments" style="clear: both;">
                <%= comment.user.name %>
                <p ><%= comment.content %></p>
             </div>
            <% end %>



      </div>

    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="topic-text">
      <p class="lef;"><strongx>トピック</strong></p>
        <p><%= @topic.content %></p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>

    <%= link_to '戻る', topics_path %>
  </div>
</div>